# Generated by Django 4.2.8 on 2023-12-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteer",
            name="broadcast",
        ),
    ]
