# Generated by Django 4.2.8 on 2023-12-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="attending",
            field=models.BooleanField(default=False),
        ),
    ]
