# Generated by Django 4.2.8 on 2023-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_attending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="attending",
            field=models.BooleanField(default=True),
        ),
    ]
