# Generated by Django 4.2.8 on 2023-12-07 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("EID", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_posters/"
                    ),
                ),
                ("ticket_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customuser",
                    ),
                ),
            ],
        ),
    ]
