# Generated by Django 4.2.8 on 2023-12-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="require_volunteers",
            field=models.BooleanField(default=False),
        ),
    ]
